apiVersion: v1
kind: ConfigMap
metadata:
  name: marcioss-configmap
data:
  SPRING_ZIPKIN_BASEURL: http://zipkin-service:9411/
  SPRING_PROFILES_ACTIVE: prod
  SPRING_CONFIG_IMPORT: configserver:http://configserver-service:8071/
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver-service:8070/eureka/
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://35.238.86.155:9411/api/v2/spans